

# How often to reload data from the nodes
reload_interval = "10s"
# If specified, a http server will serve static content here
server_address = "0.0.0.0:8080"

# Shown in the document title, if specified
#chain_name="Mainnet"
#chain_name="Goerli"
#chain_name="Ropsten"
#chain_name="Rinkeby"

# Third party providers
# infura_key = "your_key"
# infura_endpoint="https://mainnet.infura.io/v3/"
# alchemy_key = "your_key"
# alchemy_endpoint = "https://eth-mainnet.alchemyapi.io/v2/"
# etherscan_key = "your_key"
# etherscan_endpoint = "https://api.etherscan.io/api"


[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:8545"
  name = "bootnode-geth-lighthouse"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:9545"
  name = "geth-lighthouse-1"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:10545"
  name = "geth-lighthouse-2"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://78.46.91.61:11545"
  name = "geth-lighthouse-3"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://168.119.5.82:11545"
  name = "geth-lighthouse-3 (2)"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://78.46.91.61:12545"
  name = "geth-lighthouse-4"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:29545"
  name = "geth-lighthouse-localkey"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:18545"
  name = "erigon-prysm-1"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://78.46.91.61:19545"
  name = "erigon-prysm-2"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://78.46.91.61:20545"
  name = "erigon-prysm-3"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://168.119.5.82:20545"
  name = "erigon-prysm-3 (2)"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://78.46.91.61:21545"
  name = "erigon-prysm-4"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://78.46.91.61:22545"
  name = "erigon-prysm-5"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:11845"
  name = "reth-teku-1"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://78.46.91.61:12845"
  name = "reth-teku-2"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://168.119.5.82:13845"
  name = "reth-teku-3"


#[[clients]]
  # The 'infura' kind needs credentials
#  kind="infura"
#  name = "infura"
  # The rate_limit is number of requests per second allowed through
#  rate_limit=5

#[[clients]]
#
#  kind="alchemy"
#  name = "alchemy"
#  rate_limit=5

[Metrics]

#enabled = true
endpoint = "https://influx-database.yourdomain.io/"
username = "metrics"
database  = "metrics"
password  = "secret-password-goes-here"
namespace = "monitoring."