

# How often to reload data from the nodes
reload_interval = "10s"
# If specified, a http server will serve static content here
server_address = "0.0.0.0:8080"

# Shown in the document title, if specified
#chain_name="Mainnet"
#chain_name="Goerli"
#chain_name="Ropsten"
#chain_name="Rinkeby"

# Third party providers
# infura_key = "your_key"
# infura_endpoint="https://mainnet.infura.io/v3/"
# alchemy_key = "your_key"
# alchemy_endpoint = "https://eth-mainnet.alchemyapi.io/v2/"
# etherscan_key = "your_key"
# etherscan_endpoint = "https://api.etherscan.io/api"


[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:10545"
  name = "1-deployer-geth"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:10645"
  name = "2-geth-lighthouse"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:10745"
  name = "3-erigon-lighthouse"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:10845"
  name = "4-erigon-lodestar"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:10945"
  name = "5-nethermind-teku"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:11045"
  name = "6-geth-prysm"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:11145"
  name = "7-erigon-nimbus"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:11245"
  name = "8-erigon-lighthouse-newkeys"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:11345"
  name = "9-erigon-prysm"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:11445"
  name = "10-erigon-prysm-remote-key"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:11545"
  name = "11-erigon-teku"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:11645"
  name = "12-reth-lighthouse"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:11745"
  name = "13-reth-nimbus"

[[clients]]
  # The 'rpc' kind is a regular rpc-node
  kind="rpc"
  url = "http://88.99.94.109:11845"
  name = "14-reth-lodestar"

#[[clients]]
  # The 'infura' kind needs credentials
#  kind="infura"
#  name = "infura"
  # The rate_limit is number of requests per second allowed through
#  rate_limit=5

#[[clients]]
#
#  kind="alchemy"
#  name = "alchemy"
#  rate_limit=5

[Metrics]

#enabled = true
endpoint = "https://influx-database.yourdomain.io/"
username = "metrics"
database  = "metrics"
password  = "secret-password-goes-here"
namespace = "monitoring."